---
- name: Raspberry Pi setup
  hosts: raspberry
  become: true

  tasks:
    - name: Ping host
      ansible.builtin.ping:

  roles:
    - nut
    - wakelet
    - vm-builder-dashboard
    - oreilly-cache
